config/routes.rb
Rails.application.routes.draw do
  resources :students
  namespace :admin do
    root to: "#index"
  end
  devise_for :users
  resources :users
end

app/models/student.rb
class Student < ActiveRecord::Base
  validates_presence_of :caretaker_1_email, :naam
end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:user, :teacher, :admin]
  after_initialize :set_default_role, :if => :new_record?

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def set_default_role
    self.role ||= :user
  end
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_filters.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    before_filter :authenticate_admin

    def authenticate_admin
      # TODO Add authentication logic here.
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:show, :index, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to root_path, notice: 'We hebben je aanmelding voor een proefles ontvangen!' }
        format.json { render :show, status: :created, location: @student }
        NewStudentMailer.new_student_mail(@student).deliver_now
        NewStudentMailer.new_student_teacher_mail(@student).deliver_now
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:naam, :achternaam, :adres, :postcode, :plaats, :telefoon, :mobiel, :email, :geboortedatum, :caretaker_1_name, :caretaker_1_email,
:caretaker_1_mobiel,
:caretaker_2_name,
:caretaker_2_email,
:caretaker_2_mobiel,
:voorkeur_docent,
:opmerkingen)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  after_action :verify_authorized

  def index
    @users = User.all
    authorize User
  end

  def show
    @user = User.find(params[:id])
    authorize @user
  end

  def update
    @user = User.find(params[:id])
    authorize @user
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    authorize user
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_nav_links_for_auth.html.haml
- if user_signed_in?
  %p.navbar-text.navbar-right
    Logged in as:
    = link_to "#{current_user.name.capitalize}", edit_user_registration_path
    = link_to 'Sign out', destroy_user_session_path, :method=>'delete'
- else
  = link_to 'Sign in', new_user_session_path

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      = link_to 'Drumschool Hart', root_path, class: 'navbar-brand'
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'
      %p.navbar-text.navbar-right
        = render 'layouts/nav_links_for_auth'

app/views/layouts/_navigation_links.html.haml
%li
  = link_to 'Onze Docenten', '#docenten'
%li
  = link_to 'Proefles aanvragen!', new_student_path
%li
  = link_to 'Inschrijvingen', students_path if current_user && (current_user.teacher? || current_user.admin? )

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Drumschoolhart'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Drumschoolhart'}"}
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/pages/home.html.haml
/ Image Background Page Header
/ Note: The background image is set within the business-casual.css file.
%header.business-header
  .container
    .row
      .col-lg-12
        %h1.tagline Drumschool Hart
/ Page Content
.container
  %hr/
  .row
    .col-sm-8
      %h2 Drumschool Hart Haarlem
      %p Heb jij altijd al willen drummen in een band!
      %p Bij Drumschool Hart streven wij ernaar om je zo snel mogelijk een goede basis in het drummen bij te brengen zodat jij lekker met anderen muziek kan maken!

      %h3 Bij Drumschool Hart leer je o.a.:
      %ul
        %li spelen in een band
        %li drumbeats in alle stijlen van funk tot rock en van jazz tot pop
        %li melodisch slagwerk zoals marimba, vibrafoon
        %li goede basis van waaruit je kan groeien in alle muziekrichtingen en stijlen
      %hr/
    .col-sm-4
      %h2 Drumschool Hart
      %address
        %strong Kleine Houtweg 18 | Gasthuisvest 47
        = succeed "Haarlem" do
          %br/
        %br/
      %address
        %abbr{:title => "Email"} E:
        %a{:href => "mailto:#"} info@drumschoolhart.nl
        %br
        %br
        = button_to 'Meld je hier aan voor een proefles!', new_student_path, {class: 'btn btn-primary', method: 'get'}
  .row
    .col-sm-6
      %blockquote
        Drumschool Hart | Hart voor Slagwerk!
    .col-sm-6

  %hr
  .row
    %h2#docenten Onze Docenten
    %br
    .col-sm-4
      %img.img-circle.img-responsive.img-center{:alt => "", :src => "http://2.bp.blogspot.com/-wxN-aBmmqag/UTtZKNTbtiI/AAAAAAAAJ6M/iusxJm4DRQw/s1600/Ans+Rietbergen.JPG"}/
      %h2.title Ans Rietbergen
      %p
    .col-sm-4
      %img.img-circle.img-responsive.img-center{:alt => "", :src => "https://c1.staticflickr.com/9/8391/8473986365_bd6cc186d3_b.jpg"}/
      %h2.title Baz Mattie
      %p
    .col-sm-4
      %img.img-circle.img-responsive.img-center{:alt => "", :src => "https://avatars1.githubusercontent.com/u/2773366?v=4&s=460"}/
      %h2.title Tjaco Oostdijk
      %p
  %hr/
  %footer
    .row
      .col-lg-12
        %p Copyright © DrumschoolHart 2016

app/views/students/_form.html.haml
= simple_form_for(@student) do |f|
  = f.error_notification

  .form-inputs
    .form-group
      %hr
      = f.input :naam, label: 'Naam Leerling', required: true, placeholder: 'naam'
      = f.input :geboortedatum, label: 'Geboortedatum', as: :date, start_year: Date.today.year - 90, end_year: Date.today.year - 2, selected: 2008
      = f.input :caretaker_1_name, label: 'Ouder / Verzorger', required: true
      = f.input :caretaker_1_mobiel, label: 'Mobiel'
      = f.input :caretaker_1_email, label: 'Email', required: true
      = f.input :opmerkingen
  .form-actions
    = f.button :submit, value: 'Verstuur inschrijving'

app/views/students/edit.html.haml
%h1 Editing student

= render 'form'

= link_to 'Show', @student
\|
= link_to 'Back', students_path

app/views/students/index.html.haml
.container
  %h1 Inschrijvingen

  %table.table
    %thead
      %tr
        %th Leerling
        %th Geboortedatum
        %th Ouder
        %th Mobiel
        %th Email

    %tbody
      - @students.each do |student|
        %tr
          %td= student.naam
          %td= student.geboortedatum
          %td= student.caretaker_1_name
          %td= student.caretaker_1_mobiel
          %td= student.caretaker_1_email
          %td= link_to 'Show', student
          - if current_user.admin?
            %td= link_to 'Edit', edit_student_path(student)
            %td= link_to 'Destroy', student, :method => :delete, :data => { :confirm => 'Are you sure?' }

  %br

  = link_to 'Inschrijving Toevoegen', new_student_path

app/views/students/new.html.haml
.container
  .row
    .col-md-2
    .col-md-7
      %h3 Schrijf je hieronder in voor een gratis proefles.

      = render 'form'

      = link_to 'Back', students_path if current_user && (current_user.teacher? || current_user.admin? )
    .col-md-3

app/views/students/show.html.haml
.container
.row
  .col-md-2
  .col-md-7
    %p#notice= notice
    %p
      %b Naam:
      = @student.naam
    %p
      %b Geboortedatum:
      = @student.geboortedatum
    %p
      %b Ouder:
      = @student.caretaker_1_name
    %p
      %b Mobiel:
      = @student.caretaker_1_mobiel
    %p
      %b Email:
      = @student.caretaker_1_email
    %p
      %b Opmerkingen:
      = @student.opmerkingen

    = link_to 'Edit', edit_student_path(@student)
    \|
    = link_to 'Back', students_path
  .col-md-3

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<!-- Image Background Page Header -->
<!-- Note: The background image is set within the business-casual.css file. -->
<header class="business-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="tagline">Drumschool Hart</h1>
            </div>
        </div>
    </div>
</header>

<!-- Page Content -->
<div class="container">

    <hr>

    <div class="row">
        <div class="col-sm-8">
            <h2>Drumschool Hart Haarlem</h2>
            <p>Wil jij ook leren drummen dan ben je bij Drumschool Hart aan het goede adres!!</p>
            <p>Meld je nu aan voor een gratis proefles!</p>
        </div>
        <div class="col-sm-4">
            <h2>Drumschool Hart</h2>
            <address>
                <strong>Kleine Houtweg 18 | Gasthuisvest 47</strong>
                <br>Haarlem
                <br>
            </address>
            <address>
                <abbr title="Email">E:</abbr> <a href="mailto:#">info@drumschoolhart.nl</a>
            </address>
        </div>
    </div>
    <!-- /.row -->

    <hr>

    <div class="row">
        <div class="col-sm-4">
            <img class="img-circle img-responsive img-center" src="http://2.bp.blogspot.com/-wxN-aBmmqag/UTtZKNTbtiI/AAAAAAAAJ6M/iusxJm4DRQw/s1600/Ans+Rietbergen.JPG" alt="">
            <h2 class="title">Ans Rietbergen</h2>
            <p></p>
        </div>
        <div class="col-sm-4">
            <img class="img-circle img-responsive img-center" src="https://c1.staticflickr.com/9/8391/8473986365_bd6cc186d3_b.jpg" alt="">
            <h2 class="title">Baz Mattie</h2>
            <p></p>
        </div>
        <div class="col-sm-4">
            <img class="img-circle img-responsive img-center" src="http://www.nmbb.nl/images/Bio's/Tjaco_AmfJazz2-verkleind_bewerkt-4.jpg" alt="">
            <h2 class="title">Tjaco Oostdijk</h2>
            <p></p>
        </div>
    </div>
    <!-- /.row -->

    <hr>

    <!-- Footer -->
    <footer>
        <div class="row">
            <div class="col-lg-12">
                <p>Copyright &copy; DrumschoolHart 2016</p>
            </div>
        </div>
        <!-- /.row -->
    </footer>

</div>
<!-- /.container -->